{% set name = "parfive" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90dfb05d0a65d00669f5245371a4b33cbebcb5cfba86f4aad7f956984394eefd

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python
    - setuptools
    - tqdm
    - aiohttp
    - aioftp <=0.16.1  # [py=36]
    - aioftp  # [py>36]

test:
  imports:
    - parfive
  requires:
    - pytest
    - pytest-localserver
    - pytest-asyncio
    - pytest-socket
  commands:
    - pytest --pyargs parfive

about:
  home: https://parfive.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parallel file downloader using asyncio.
  doc_url: https://parfive.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Cadair
    - nabobalis
